### ISSUE TITLE
Callback on the end of text add typing

### ISSUE THREAD

**Issue by jedrzejchalubek** [albburtsev/jquery.typist#4]
It will be really usefull.

```js
.typistAdd( [text], [callback] )
```

**Comment by albburtsev** [comment]
I got it.

**Comment by albburtsev** [comment]
I thought again about this and decided don't add callback. [Events](https://github.com/albburtsev/jquery.typist#events) are completely enough for solving this problem:

```js
$('.container')
  .typistAdd('Some text')
  .on('end_type.typist', function() {
    // Do something
  });
```

**Comment by jedrzejchalubek** [comment]
No. This isn't solving it at all. `end_type.typist` event fires at end of typing every future line.
I would want call callback only when specifed line was typed and only here.

**Comment by albburtsev** [comment]
Enjoy!

**Comment by jedrzejchalubek** [comment]
Great! Thanks :+1:
