### ISSUE TITLE
Feature: Random delay between each character

### ISSUE THREAD

**Issue by lukerollans** [albburtsev/jquery.typist#5]
As the title suggests, I think the ability to add a random delay between each character typed would optionally give the effect that a human is typing the text.

A good default would be, say, between 10ms and 30ms, but would also be configurable via an option

**Comment by albburtsev** [comment]
Interesting idea, I try to do this in the coming days.

**Comment by lukerollans** [comment]
I'll try to open a PR if I have time and I see that you haven't gotten around to it.. I'm not hopeful though! :)

**Comment by albburtsev** [comment]
Ok.
