### ISSUE TITLE
Newline characters are lost when .typistRemove is called

### ISSUE THREAD

**Issue by HolyThunder** [albburtsev/jquery.typist#6]
While using jquery.typist on a paragraph element, and taking advantage of '\n' to start writing in the next line, the text remains formatted (with newlines and all) until the first time .typistRemove() is called. At that point, the text reformats to fill the element in which it is in, disregarding '\n' characters.

**Comment by albburtsev** [comment]
Got it, wait fix for a few days.

**Comment by albburtsev** [comment]
Fixed in v0.0.6.
