### ISSUE TITLE
Callback doesn't wait for typing to complete

### ISSUE THREAD

**Issue by alkah3st** [albburtsev/jquery.typist#7]
When I call typistRemove:

``$("target").typistRemove( 30, myCallback );``

It doesn't wait for the typing to finish before doing the callback, it calls it immediately.

**Comment by albburtsev** [comment]
Hmm, I will check it.

**Comment by albburtsev** [comment]
Please, check your reports.
Callback called exactly [at the end of removing](http://jsfiddle.net/rms8qcw3/).
