### ISSUE TITLE
Repeat messages

### ISSUE THREAD

**Issue by pkollitsch** [albburtsev/jquery.typist#8]
Hi, I have the following sequence of typist lines:

  ```     
jQuery('.typist')
            .typist({
                text: ''
            })
            .typistPause(2000) // 2 sec
            .typistAdd('line1')
            .typistPause(2000) // 2 sec
            .typistRemove(26)
            .typistAdd('line2')
            .typistPause(2000) // 2 sec
            .typistRemove(22)
            .typistAdd('line3')
            .typistPause(2000) // 2 sec
            .typistRemove(38);      
 ```             

how do I achieve that it starts repeating itself after each run?

**Comment by HolyThunder** [comment]
This isn't an issue, and shouldn't be posted here. What you want to do can be achieved using normal javascript + a callback on the last typistRemove(), such as typistRemove( [length], [callback] ). You should refer to stackoverflow for further questions and not github's issue system.

**Comment by pkollitsch** [comment]
nah, i used another library whose documentation covered this case. thanks.
